### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by Felisinnn** [JamCoreModding/shut-up-gl-error#2]
Every time I boot my modded instance hundreds of these are created: 

[19:31:47] [Thread-43/INFO]: OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Size and/or offset out of range.' 

I have no idea if this has anything to do with your mod, and I would like to know if I should be concerned about it. Excuse my ignorance. 

Here's the full log:
https://mclo.gs/UzLHwbO

**Comment by Jamalam360** [comment]
Hi there,

I'm not sure what will be causing this or if it will cause any issues with your game, but I can say it is unrelated to this mod. 

Good luck
